### ISSUE TITLE
[CONNIO EDGE] Add edge nodes to send data from device to the platform

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#12]
[**See next comments for changes. We might need to change node fields accordingly**]

This is for the cases where Nodered works in a device. Selected device will write a data point into the selected property using device key meaning we will be able to write into all device properties including `private` and `protected` ones.

If property is selected make sure that the flowing value is converted to a data point as expected by the platform.

The data will be written via MQTT API.

<img width="492" alt="Screen Shot 2019-11-26 at 9 54 47 PM" src="https://user-images.githubusercontent.com/2756202/69699618-41ea3780-109d-11ea-8c4e-1d79191c751c.png">

**Details**

We need only 3 fields on this dialog:

0. Connio mqtt endpoint address and port (default will be mqtt.connio.cloud + 1883)
1. Device key id
2. Device key secret
3. Property name

The node must have only one input. 

Example usage is as the following:

- IoT enthusiast will deploy NodeRed to his device (e.g. RaspPi). 
- He will install connio package
- From the "Connio Edge"  group he will select this one
- He will install another node to read IO ports of the RaspPi
- He will connect the output of the IO PORT reader node to the input of this one
- our node will write flowing data into the given device and property via MQTT

**Important**

- Property combo will be populated with device's properties automatically when the credentials are provided via REST API
- Device id will be collected automatically using given credentials via REST API
- The very first item in the list will be <JSON>. When selected that means the developer want to provide data in JSON format.

For example, if `temperature` is selected in the list, the MQTT topic will as following:
.../devices/{id}/properties/temperature and the data will be in raw format.

if `JSON` is selected in the list, the MQTT topic will as following:
.../devices/{id}/properties/json.

See the documentation for details.

**Comment by bmrb** [comment]
<img width="517" alt="Screen Shot 2019-12-02 at 10 50 17 PM" src="https://user-images.githubusercontent.com/2756202/70027325-be29c280-1556-11ea-8a51-3755a14fa9f5.png">

**Comment by EvanJ0hnson** [comment]
`JSON` is moved into Property selector and renamed to `Data Feed Format`
<img width="499" alt="Screen Shot 2019-12-12 at 3 52 12 PM" src="https://user-images.githubusercontent.com/1561359/70713658-890c3580-1cf7-11ea-97e7-d6ca697a0c0e.png">
**Version** `0.5.5`

**Comment by EvanJ0hnson** [comment]
Added `[Connio Edge] device in` node

**Version** `0.5.6`

**Comment by EvanJ0hnson** [comment]
- Introduce "gateway in" node
- handle multiple MQTT connections

**Version** `0.5.8`

**Comment by EvanJ0hnson** [comment]
- Don’t show already selected devices in the list
  `gateway in`, `gateway out`, `device in`

**Version** `0.5.9`

**Comment by EvanJ0hnson** [comment]
- `edge-gateway in` Subscribe on linked devices
  

**Version** `0.5.10`
