### ISSUE TITLE
Connio MQTT node issues summary

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#18]
The following issues need to be solved. Test done by installing Connio package on Node RED v1.0.3.  

- [x]  Fix account switching bug. Replacing originally configured account with some new account doesn't work as expected. API Clients and App comb boxes do not get populated properly.
- [x] Error messages need to be improved. Problem like the one described above needs better explanation.
- [x] Node Help and Description texts need to be written [EB]
- [x] Replace account name with account friendly name
- [x] Set default Deployment URL to `https://api-auth.connio.cloud`
- [x] Change Connio package name to `Connio Cloud`
- [x] Connio MQTT connected to DEbug doens't show any value
- [ ] Connio group doesn't dissapear after connio package is uninstalled until Node RED page is refreshed

**Comment by EvanJ0hnson** [comment]
> Connio group doesn't dissapear after connio package is uninstalled until Node RED page is refreshed

I think this is how NodeRED works. Tested on other nodes, they all behave the same

**Comment by EvanJ0hnson** [comment]
> Node Help and Description texts need to be written [EB]

Issues #40 and #41
