### ISSUE TITLE
Always says Device is not connected to the gateway even when it is 

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#26]
This device is linked to the gateway but when DEPLOY is pressed it gives the following error.

Tested after switched to another account.

Also the error message should say "....is not **linked**..." 

<img width="660" alt="Screen Shot 2019-12-10 at 9 44 18 PM" src="https://user-images.githubusercontent.com/2756202/70595588-9b239200-1b98-11ea-84f8-14c7fa5b05a6.png">

**Comment by EvanJ0hnson** [comment]
@bmrb 
Which version is that, `0.5.0-beta.2` or `0.5.0`? `0.5.0-beta.2` contained a bug when the error notification showed up  on each deploy/page reload

**Comment by EvanJ0hnson** [comment]
Which version is that? 0.5.0-beta.2 or 0.5.0? 0.5.0-beta.2 contained a bug when the error notification showed up on each deploy/page reload

**Comment by EvanJ0hnson** [comment]
> Also the error message should say "....is not linked..."

Version `0.5.3`
