### ISSUE TITLE
When switched to another account, device list doesn't get updated immediately

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#27]
<img width="1515" alt="Screen Shot 2019-12-10 at 9 36 55 PM" src="https://user-images.githubusercontent.com/2756202/70595772-079e9100-1b99-11ea-9cfe-a9a5146eac30.png">

**Comment by EvanJ0hnson** [comment]
That is true, we did’t watch for internal changes in account node.

Fixed
**Version** `0.5.2`
