### ISSUE TITLE
Unclear wearning is given

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#29]
I am getting this warning for no apparent reasons. I created device first, then added gateway, then the MQTT Broker.

<img width="1402" alt="Screen Shot 2019-12-10 at 10 12 34 PM" src="https://user-images.githubusercontent.com/2756202/70596589-256cf580-1b9b-11ea-9c87-482af1643b14.png">

**Comment by EvanJ0hnson** [comment]
@bmrb You need explicitly open each node after creation (in this case `Edge MQTT`) and press `Done` even if everything is set correctly, otherwise NodeRED will not propagate data to the backend part of the particular node
