### ISSUE TITLE
Suggested node name changes

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#30]
<img width="1388" alt="Screen Shot 2019-12-10 at 10 41 12 PM" src="https://user-images.githubusercontent.com/2756202/70598199-23a53100-1b9f-11ea-97f9-c4d2ee894e73.png">

**Comment by EvanJ0hnson** [comment]
@bmrb `device` and `gateway` icons are replaced with the following ones:

![Screen Shot 2019-12-11 at 2 33 42 PM](https://user-images.githubusercontent.com/1561359/70618179-44af6580-1c23-11ea-916f-51bbd84caa9b.png)

**Comment by bmrb** [comment]
Can you change the gateway icon as shown below:

<img width="31" alt="Screen Shot 2019-12-11 at 1 43 54 PM" src="https://user-images.githubusercontent.com/2756202/70663033-55a8a880-1c1c-11ea-8f50-14e8a30212d3.png">

**Comment by bmrb** [comment]
# Connio Edge
device in
device out
gateway
connio in

# Connio Cloud
connio out
connio in  (for App or Device method/property writing node - using user key or API Client key)

**Comment by EvanJ0hnson** [comment]
Done
<img width="619" alt="Screen Shot 2019-12-12 at 3 01 55 PM" src="https://user-images.githubusercontent.com/1561359/70710593-8ce88980-1cf0-11ea-8a0c-a240741dc4ce.png">

**Version** `0.5.5`

**Comment by EvanJ0hnson** [comment]
<img width="621" alt="Screen Shot 2019-12-12 at 3 14 09 PM" src="https://user-images.githubusercontent.com/1561359/70711249-1cdb0300-1cf2-11ea-9b3b-42deb510bcd1.png">

**Version** `0.5.5`
