### ISSUE TITLE
Improve package description page

### ISSUE THREAD

**Issue by bmrb** [connio/node-red-contrib-connio#39]
We like to add the following sections and text to the package page:

<img width="1171" alt="Screen Shot 2019-12-11 at 2 45 45 PM" src="https://user-images.githubusercontent.com/2756202/70667223-2ba7b400-1c25-11ea-98a9-986d9950c54d.png">

**Title**: Node-RED nodes for the Connio platform

## Overview

A collection of Node-RED nodes to communicate with the Connio platform. The first group of nodes (Connio Edge) allows you to bi-directionally communicate with the platform from your devices and gateways. You can use these nodes from a Node-RED instance installed within your device. The second group (Connio Cloud) allows you to connect external services to the platform to consume device data and send device commands easily.

Connio offers an Internet of Things (IoT) platform that enables businesses to quickly connect, integrate and orchestrate their products and operations within IoT ecosystem.

You can register to the Connio platform at https://app.connio.cloud.
Check the platform documentation at https://docs.connio.com.

## Install 

If installing from within Node-RED, use the Manage Palette menu command and search for `node-red-contrib-connio`.

Or, from a command line within your Node-RED user directory, enter:

`npm install node-red-contrib-connio`

## Configuration

Connio nodes will have an Account and Deployment property which must be configured. Deployment property allows you to select the Connio deployment or host that you like to use in your flow. Account property allows you to select the Connio account you like to use. You only have to set this configuration once and use it in all your nodes.

<img width="510" alt="Screen Shot 2019-12-11 at 6 29 25 PM" src="https://user-images.githubusercontent.com/2756202/70677497-2efe6800-1c44-11ea-8d19-b59e6ea773a3.png">

<img width="514" alt="Screen Shot 2019-12-11 at 6 26 15 PM" src="https://user-images.githubusercontent.com/2756202/70677503-358cdf80-1c44-11ea-911b-988019ba63cf.png">

## Usage

**Connio Edge** nodes are designed to be used by remote devices for communicating with the platform.

**Connio Cloud** nodes are designed to be used by external systems (web services, mobile apps, etc...) for communicating with the platform.

See node documentation to better understand each node usage.

## Copyright and license

Copyright 2019, 2020 Connio Inc. under the Apache 2.0 license.

**Comment by EvanJ0hnson** [comment]
@bmrb Regarding `Maintainers` field — looks like it is `npm` username, so there is no way to change it to `Connio Inc.`

**Comment by EvanJ0hnson** [comment]
**Version** `0.5.5`

**Comment by bmrb** [comment]
See proper title above.

<img width="1226" alt="Screen Shot 2019-12-12 at 9 42 44 AM" src="https://user-images.githubusercontent.com/2756202/70735845-dff81780-1cc3-11ea-98b1-0bf8b6255682.png">

**Comment by bmrb** [comment]
(1) Put links to separate lines:

You can register to the Connio platform at https://app.connio.cloud.  
Check the platform documentation at https://docs.connio.com.

(2) Also add this link (as a separate line) to the overview section: 

See Node-RED tutorial at https://docs.connio.com/docs/integration-node-red.

**Comment by EvanJ0hnson** [comment]
> (1) Put links to separate lines

Fixed

> (2) Also add this link (as a separate line) to the overview section:

Done

Regarding the title, looks like they use a description field from package.json instead of a header in README.md. I have updated the description to match the title. We will see once the version will be published

**Version** `0.5.6`
